const starterBucket=[
['Take a roommate photo on the first day of school','Roommates'],['Have a 1002 dinner','Food'],['Go on a spontaneous road trip','Adventure'],['Have a themed house party','Nights Out'],['Watch the sunrise together','Memories'],['Watch the sunset together','Memories'],['Have a roommate movie marathon','Roommates'],['Cook a three-course dinner together','Food'],['Go somewhere none of us have been','Adventure'],['Have a picnic','Adventure'],['Take roommate photos','Memories'],['Have a holiday dinner','Roommates'],['Go to a concert','Nights Out'],['Have a karaoke night','Nights Out'],['Do a random day trip','Adventure'],['Have a yes day','Chaos'],['Go out for breakfast after a night out','Food'],['Recreate an old group photo','Memories'],['Have a sleepover even though we live together','Roommates'],['Make the 1002 playlist','Memories'],['Go skating','Adventure'],['Have a beach day','Adventure'],['Try a new restaurant','Food'],['Have a PowerPoint night','Chaos'],['Make matching something','Roommates'],['Have a game night','Roommates'],['Take a Polaroid for a bucket-list activity','Memories'],['Have a fancy roommate dinner','Food'],['Go on a hike','Adventure'],['Have a no-phone dinner','Roommates'],['Do a thrift-shopping day','Adventure'],['Have a baking night','Food'],['Go to a sporting event','Adventure'],['Have a themed photoshoot','Memories'],['Stay up until sunrise','Chaos'],['Make a time capsule','Memories'],['Have a roommate awards night','Chaos'],['Write letters to open after graduation','Memories'],["Visit each other's hometowns",'Adventure'],['Take a spontaneous train or bus somewhere','Adventure'],['Be tourists in our own city','Adventure'],['Go camping','Adventure'],['Have a pool day','Adventure'],['Do a 1002 Secret Santa','Roommates'],['Have a spa night','Roommates'],['Make a roommate scrapbook','Memories'],['Have a formal dinner and dress up','Food'],['Go bowling','Adventure'],['Have a karaoke competition','Chaos'],['Take a group photo in the same spot every month','Memories']
].map((x,i)=>({id:i+1,title:x[0],category:x[1],done:false}));
const defaultState={bucket:starterBucket,memories:[{id:1,text:'The beginning of our last year together ♡',by:'1002',date:'September 2026'}],events:[{id:1,title:'First day of our final year',date:'September 2026',note:'The beginning of the last chapter.'},{id:2,title:'1002 Holiday Dinner',date:'December 2026',note:'Dress up, cook together, take too many photos.'},{id:3,title:'Graduation',date:'Spring 2027',note:'We actually did it.'}],photos:[]};
let state=JSON.parse(localStorage.getItem('1002-state')||'null')||defaultState;let page='home';let bucketFilter='All';
const app=document.querySelector('#app'),backdrop=document.querySelector('#modalBackdrop'),modal=document.querySelector('#modal');
function save(){localStorage.setItem('1002-state',JSON.stringify(state))}function completed(){return state.bucket.filter(x=>x.done).length}function pct(){return Math.round(completed()/state.bucket.length*100)||0}
function setPage(p){page=p;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===p));render();window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>setPage(b.dataset.page));document.querySelector('[data-go]').onclick=()=>setPage('home');
function render(){({home:renderHome,bucket:renderBucket,album:renderAlbum,year:renderYear,memories:renderMemories}[page])()}
function renderHome(){app.innerHTML=`<p class="eyebrow">Ella · Keira · Megan · Tristan</p><h1 class="hero-title">Our <em>last year.</em><br>Let's make it count.</h1><p class="sub">One place for everything we want to do, every photo we take, and all the little things we never want to forget.</p><section class="hero-card"><div class="progress-row"><div><div class="progress-number">${completed()} / ${state.bucket.length}</div><div class="progress-label">memories waiting to happen</div></div><strong>${pct()}%</strong></div><div class="progress-track"><div class="progress-fill" style="width:${pct()}%"></div></div></section><div class="section-head"><h2>What are we doing?</h2></div><div class="quick-grid"><button class="quick-card" onclick="setPage('bucket')"><span class="icon">✓</span><strong>Bucket List</strong><small>${state.bucket.length-completed()} left to do</small></button><button class="quick-card" onclick="setPage('album')"><span class="icon">▧</span><strong>1002 Album</strong><small>${state.photos.length} photos</small></button><button class="quick-card" onclick="setPage('year')"><span class="icon">♡</span><strong>Our Year</strong><small>${state.events.length} moments planned</small></button><button class="quick-card" onclick="setPage('memories')"><span class="icon">✦</span><strong>Memories</strong><small>${state.memories.length} things saved</small></button></div><div class="section-head"><h2>Note to us</h2></div><div class="quote-card"><p>“These are the days we'll wish we could come back to.”</p><small>— 1002, one last year</small></div>`}
function renderBucket(){let cats=['All',...new Set(state.bucket.map(x=>x.category))];let items=bucketFilter==='All'?state.bucket:state.bucket.filter(x=>x.category===bucketFilter);app.innerHTML=`<div class="page-head"><div><p class="eyebrow">${completed()} of ${state.bucket.length} complete</p><h1 class="page-title">Bucket List</h1></div><button class="add-btn" onclick="openBucketModal()">+</button></div><div class="filter-row">${cats.map(c=>`<button class="chip ${c===bucketFilter?'active':''}" onclick="bucketFilter='${c}';renderBucket()">${c}</button>`).join('')}</div><div class="bucket-list">${items.map(x=>`<article class="bucket-item ${x.done?'done':''}"><button class="check" onclick="toggleBucket(${x.id})">${x.done?'✓':''}</button><div><div class="item-title">${esc(x.title)}</div><div class="item-meta">${x.category}</div></div><span class="category-dot">${iconFor(x.category)}</span></article>`).join('')}</div>`}
function toggleBucket(id){let x=state.bucket.find(x=>x.id===id);x.done=!x.done;save();renderBucket()}
function iconFor(c){return ({Food:'🍝',Adventure:'☀',Memories:'♡','Nights Out':'✦',Roommates:'⌂',Chaos:'☻'})[c]||'♡'}
function renderAlbum(){app.innerHTML=`<div class="page-head"><div><p class="eyebrow">our camera roll</p><h1 class="page-title">1002 Album</h1></div></div><div class="upload-card"><div style="font-size:28px;margin-bottom:8px">▧</div><strong>Add a memory</strong><p class="sub" style="margin:5px 0 14px">Photos stay on this device in Version 1.</p><input id="photoInput" type="file" accept="image/*" hidden onchange="addPhoto(event)"><button onclick="document.querySelector('#photoInput').click()">Choose photo</button></div>${state.photos.length?`<div class="album-grid">${state.photos.map((p,i)=>`<article class="photo-card" style="--r:${i%2?1.5:-1.2}deg"><div class="photo-placeholder"><img src="${p.data}" alt="1002 memory"></div><p>${esc(p.caption||'1002 ♡')}</p></article>`).join('')}</div>`:`<div class="empty">Your shared-looking scrapbook starts here.<br>Add the first photo of the year ♡</div>`}`}
function addPhoto(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{openModal(`<h2>Caption this memory</h2><div class="field"><label>Caption</label><input id="caption" placeholder="What happened?"></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" id="savePhoto">Save photo</button></div>`);document.querySelector('#savePhoto').onclick=()=>{state.photos.unshift({id:Date.now(),data:r.result,caption:document.querySelector('#caption').value});save();closeModal();renderAlbum()}};r.readAsDataURL(f)}
function renderYear(){app.innerHTML=`<div class="page-head"><div><p class="eyebrow">september → graduation</p><h1 class="page-title">Our Year</h1></div><button class="add-btn" onclick="openEventModal()">+</button></div><div class="timeline">${state.events.map(e=>`<article class="event"><div class="event-date">${esc(e.date)}</div><h3>${esc(e.title)}</h3><div class="item-meta">${esc(e.note||'')}</div></article>`).join('')}</div>`}
function renderMemories(){app.innerHTML=`<div class="page-head"><div><p class="eyebrow">don't forget this</p><h1 class="page-title">Memories</h1></div><button class="add-btn" onclick="openMemoryModal()">+</button></div><div class="memory-grid">${state.memories.map((m,i)=>`<article class="memory" style="--r:${[-.6,.5,-.2][i%3]}deg"><p>${esc(m.text)}</p><small>${esc(m.by)} · ${esc(m.date)}</small></article>`).join('')}</div>`}
function openBucketModal(){openModal(`<h2>Add to the list</h2><div class="field"><label>What should 1002 do?</label><input id="newBucket" placeholder="e.g. Go to a concert"></div><div class="field"><label>Category</label><select id="newCat"><option>Roommates</option><option>Adventure</option><option>Food</option><option>Nights Out</option><option>Memories</option><option>Chaos</option></select></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="addBucket()">Add it</button></div>`)}
function addBucket(){let v=document.querySelector('#newBucket').value.trim();if(!v)return;state.bucket.push({id:Date.now(),title:v,category:document.querySelector('#newCat').value,done:false});save();closeModal();renderBucket()}
function openMemoryModal(){openModal(`<h2>Save this forever</h2><div class="field"><label>Memory / quote / inside joke</label><textarea id="memoryText" placeholder="Remember when..."></textarea></div><div class="field"><label>Who said / added it?</label><select id="memoryBy"><option>Ella</option><option>Keira</option><option>Megan</option><option>Tristan</option><option>1002</option></select></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="addMemory()">Save memory</button></div>`)}
function addMemory(){let v=document.querySelector('#memoryText').value.trim();if(!v)return;state.memories.unshift({id:Date.now(),text:v,by:document.querySelector('#memoryBy').value,date:new Date().toLocaleDateString('en-CA',{month:'long',year:'numeric'})});save();closeModal();renderMemories()}
function openEventModal(){openModal(`<h2>Add to our year</h2><div class="field"><label>Plan</label><input id="eventTitle" placeholder="e.g. 1002 Christmas Dinner"></div><div class="field"><label>Date</label><input id="eventDate" type="date"></div><div class="field"><label>Note</label><input id="eventNote" placeholder="Optional"></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="addEvent()">Add plan</button></div>`)}
function addEvent(){let t=document.querySelector('#eventTitle').value.trim(),d=document.querySelector('#eventDate').value;if(!t||!d)return;let formatted=new Date(d+'T12:00:00').toLocaleDateString('en-CA',{month:'long',day:'numeric',year:'numeric'});state.events.push({id:Date.now(),title:t,date:formatted,note:document.querySelector('#eventNote').value});save();closeModal();renderYear()}
function openModal(html){modal.innerHTML=html;backdrop.classList.remove('hidden')}function closeModal(){backdrop.classList.add('hidden')}backdrop.onclick=e=>{if(e.target===backdrop)closeModal()};function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}render();
